# Generated by Django 5.0.6 on 2024-05-14 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
