# Generated by Django 5.0.6 on 2024-05-14 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userfile_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_entries', to='users.userfile')),
            ],
            options={
                'unique_together': {('user_file', 'user')},
            },
        ),
        migrations.AddField(
            model_name='userfile',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_files', through='users.SharedWith', to=settings.AUTH_USER_MODEL),
        ),
    ]
