# Generated by Django 5.0.6 on 2024-05-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
