# Generated by Django 5.0.3 on 2024-05-24 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userfile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FileSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='users.userfile')),
            ],
        ),
    ]
