version: '3'
services:
  postgres:
    container_name: postgres_cont
    image: postgres:latest
    environment:
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "utyfull"
      POSTGRES_PASSWORD: "1215010q"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - main_db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utyfull -d main_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin_cont
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: "serg_misha1@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "215010"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var//lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres



volumes:
  main_db-data:
  pgadmin-data:


networks:
  postgres:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.0.0/16
         gateway: 172.10.5.254
         aux_addresses:
          postgres: 172.10.0.2
    