# Generated by Django 5.0.3 on 2024-03-21 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTable',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('pssword', models.CharField(max_length=200)),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignDocTable',
            fields=[
                ('foreign_doc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foreign_user_id', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.authtable')),
            ],
        ),
        migrations.CreateModel(
            name='OwnDocTable',
            fields=[
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.authtable')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTable',
            fields=[
                ('foreign_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foreign_user_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.owndoctable')),
            ],
        ),
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('comments', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('foreign_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.statustable')),
            ],
        ),
    ]
