# Generated by Django 5.0.3 on 2024-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_owndoctable_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owndoctable',
            name='file',
            field=models.FileField(default='default_file.txt', upload_to='data_file'),
        ),
    ]
